Repository SasView/sasmodels, pull requests merged in 2023-08, with the labels that each got.

#572 fixes docs so math will display correctly
  sasmodels/models/lamellar_hg.py
Labels: minor, SasModels Documentation

#574 Disable name check
  sasmodels/direct_model.py
Labels: bug, DiscussAtTheCall

#575 Re-enable parameter name checking in kernel call
  sasmodels/direct_model.py
  sasmodels/jitter.py
Labels: DiscussAtTheCall
